=== tedy-art/Python/100.The_K_Academy/Mysql Setup & Documentaion/Mysql Setup & Documentaion/MySql_Setup/MySQL GUI Tools 5.0/xml/mysqladmin_startup_variables_description.dtd
<!ENTITY % pos_and_id "position CDATA #REQUIRED id ID #IMPLIED">

<!ELEMENT gui_description (page+)>

<!ELEMENT page (caption, description, group+)>
<!ATTLIST page %pos_and_id;>

<!ELEMENT group (caption,(checkbox|spinedit|textedit|dropdownbox)+ )>
<!ATTLIST group %pos_and_id; version_start CDATA '4.0' version_end CDATA #IMPLIED>
<!-- version_start and version_end indicate for what mysql-server-versions this group-element should be shown. -->


<!-- Now follow the GUI-elements -->

<!ENTITY % widget_elements "caption,default_value+,description, alt_name*">
<!ENTITY % widget_elements_no_default_value "caption,default_value*,description, alt_name*">

<!ENTITY % widget_attrs "position NMTOKEN #REQUIRED id ID #REQUIRED  multiple (yes|no) 'no' version_start CDATA '4.0' version_end CDATA #IMPLIED platform (linux|windows|macos|all) 'all'">


<!ELEMENT checkbox (%widget_elements;)>
<!ATTLIST checkbox %widget_attrs; is_boolean (yes|no) 'no' invert (yes|no) 'no'>

<!ELEMENT spinedit ( %widget_elements; , unitcontrolbox?)>
<!ATTLIST spinedit %widget_attrs;>

<!ELEMENT unitcontrolbox EMPTY>
<!ATTLIST unitcontrolbox type CDATA #REQUIRED>

<!ELEMENT textedit (%widget_elements_no_default_value;)>
<!ATTLIST textedit %widget_attrs; type (normal|ip|directory|file|innodbfilepath|memo|repldodb) "normal">

<!ELEMENT dropdownbox (%widget_elements;, items+)>
<!ATTLIST dropdownbox %widget_attrs;>
<!ELEMENT items (item+)>
<!ELEMENT item (#PCDATA)>

<!ELEMENT caption (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT default_value (#PCDATA)>
<!ATTLIST default_value version CDATA "4.0" platform (linux|windows|macos|all) 'all'>
<!ELEMENT alt_name (#PCDATA)>

=== tedy-art/Python/100.The_K_Academy/Mysql Setup & Documentaion/Mysql Setup & Documentaion/MySql_Setup/MySQL GUI Tools 5.0/xml/mysqladmin_startup_variables_description.xml
<?xml version="1.0" ?>
<!DOCTYPE gui_description SYSTEM "mysqladmin_startup_variables_description.dtd">
<gui_description>

  <page position="1">
    <caption>General Parameters</caption>
    <description>This page contains general parameters for the MySQL server.</description>

    <group position="2">
      <caption>Networking</caption>
      <checkbox position="2" id="skip-networking">
        <caption>Disable networking</caption>
        <default_value>Unchecked</default_value>
        <description>Don't allow connections via TCP/IP.</description>
      </checkbox>
      <spinedit position="3" id="port">
        <caption>TCP Port:</caption>
        <default_value version="4.0">3306</default_value>
        <description>Port number to use for connections.</description>
      </spinedit>
      <checkbox position="3" id="enable-named-pipe">
        <caption>Enable named pipes</caption>
        <default_value>Unchecked</default_value>
        <description>Allow connections via named pipes (Windows NT+ only). Note: you can specify a pipe name on the advanced network page, if required.</description>
      </checkbox>
    </group>
    <group position="3">
      <caption>Directories</caption>
      <textedit position="1" id="basedir" type="directory">
        <caption>Base directory:</caption>
        <description>Path to installation directory. All paths are usually resolved relative to this.</description>
      </textedit>
      <textedit position="2" id="datadir" type="directory">
        <caption>Data directory:</caption>
        <description>Path to the database root</description>
      </textedit>
      <textedit position="3" id="tmpdir" type="directory">
        <caption>Temp directory:</caption>
        <default_value></default_value>
        <description>Path to the temporary directory.</description>
      </textedit>
    </group>
    <group position="4">
      <caption>Memory usage</caption>
      <spinedit position="1" id="key_buffer_size">
        <caption>Key buffer:</caption>
        <default_value>8192k</default_value>
        <description>The size of the buffer used for index blocks. Increase this to get better index handling (for all reads and multiple writes) to as much as you can afford; 64M on a 256M machine that mainly runs MySQL is quite common.</description>
        <alt_name>key_buffer</alt_name>
        <unitcontrolbox type="k;M" />
      </spinedit>
      <spinedit position="2" id="sort_buffer_size">
        <caption>Sort buffer size</caption>
        <default_value>2M</default_value>
        <description>Each thread that needs to do a sort allocates a buffer of this size.</description>
        <alt_name>sort_buffer</alt_name>
        <unitcontrolbox type="k;M" />
      </spinedit>
    </group>

    <group position="5">
      <caption>General</caption>

      <dropdownbox position="1" id="default-table-type" version_start="4.0" version_end="4.0">
        <caption>Default table type:</caption>
        <default_value>myisam</default_value>
        <description>If no specific storage engine/table type is defined in an SQL-Create statement the default type will be used.</description>
        <items>
          <item>MyIsam=myisam</item>
          <item>InnoDB=innodb</item>
          <item>BDB=bdb</item>
          <item>Heap=heap</item>
          <item>Isam=isam</item>
        </items>
      </dropdownbox>
      <dropdownbox position="1" id="default-storage-engine" version_start="4.1">
        <caption>Default storage engine:</caption>
        <default_value>myisam</default_value>
        <description>If no specific storage engine/table type is defined in an SQL-Create statement the default type will be used.</description>
        <alt_name>default-table-type</alt_name>
        <items>
          <item>MyIsam=myisam</item>
          <item>InnoDB=innodb</item>
          <item>Falcon=falcon</item>
          <item>BDB=bdb</item>
          <item>Heap=heap</item>
        </items>
      </dropdownbox>
    </group>

  </page>

  <page position="2">
    <caption>MyISAM Parameters</caption>
    <description>Edit MyISAM specific parameters on this page.</description>
    <group position="1">
      <caption>General</caption>
      <checkbox position="1" id="concurrent-insert" is_boolean="yes">
        <caption>Use concurrent inserts</caption>
        <default_value>Checked</default_value>
        <description>Use concurrent insert with MyISAM.</description>
      </checkbox>
      <checkbox position="2" id="skip-locking" is_boolean="yes" version_end="4.1">
        <caption>Disable external locking</caption>
        <default_value>Unchecked</default_value>
        <description>Do not use system (external) locking. With locking enabled you can run myisamchk to test (not repair) tables while the MySQL server is running.</description>
      </checkbox>
      <checkbox position="2" id="external-locking" is_boolean="yes" version_start="4.1">
        <caption>Use external locking</caption>
        <default_value>Unchecked</default_value>
        <description>Use system (external) locking. With this option enabled you can run myisamchk to test (not repair) tables while the MySQL server is running.</description>
      </checkbox>
    </group>
    <group position="2">
      <caption>Fulltext search</caption>
      <spinedit position="1" id="ft_min_word_len">
        <caption>Minimum word length:</caption>
        <default_value>4</default_value>
        <description>The minimum length of the word to be included in a FULLTEXT index. Note: FULLTEXT indexes must be rebuilt after changing this variable.</description>
      </spinedit>
      <spinedit position="2" id="ft_max_word_len">
        <caption>Maximum word length:</caption>
        <default_value>84</default_value>
        <description>The maximum length of the word to be included in a FULLTEXT index. Note: FULLTEXT indexes must be rebuilt after changing this variable.</description>
      </spinedit>
      <spinedit position="3" id="ft_query_expansion_limit">
        <caption>Query expansion limit:</caption>
        <default_value>4</default_value>
        <description>Number of best matches to use for query expansion.</description>
      </spinedit>
      <textedit position="4" id="ft_stopword_file" type="file">
        <caption>Stopword file:</caption>
        <default_value></default_value>
        <description>Use stopwords from this file instead of built-in list.</description>
      </textedit>
    </group>
    <group position="4">
      <caption>Advanced Settings</caption>
      <spinedit position="1" id="myisam_block_size">
        <caption>Block size:</caption>
        <default_value>1024</default_value>
        <description>Block size to be used for MyISAM index pages.</description>
      </spinedit>
      <spinedit position="2" id="myisam_max_extra_sort_file_size">
        <caption>Extra sort file size:</caption>
        <default_value>256M</default_value>
        <description>Used to help MySQL to decide when to use the slow but safe key cache index create method.</description>
        <unitcontrolbox type="k;M" />
      </spinedit>
      <spinedit position="3" id="myisam_max_sort_file_size">
        <caption>Max sort file size:</caption>
        <default_value>2047M</default_value>
        <description>Don't use the fast sort index method to created index if the temporary file would get bigger than this.</description>
        <unitcontrolbox type="k;M" />
      </spinedit>
      <spinedit position="4" id="myisam_repair_threads">
        <caption>Number of repair threads:</caption>
        <default_value>1</default_value>
        <description>Number of threads to use when repairing MyISAM tables.The value of 1 disables parallel repair.</description>
      </spinedit>
      <spinedit position="5" id="myisam_sort_buffer_size">
        <caption>MyIsam Sort buffer size:</caption>
        <default_value>8192k</default_value>
        <description>The buffer that is allocated when sorting the index when doing a REPAIR or when creating indexes with CREATE INDEX or ALTER TABLE.</description>
        <unitcontrolbox type="k;M" />
      </spinedit>
    </group>
  </page>
  <page position="3">
    <caption>InnoDB Parameters</caption>
    <description>All relevant InnoDB Parameters.</description>
    <group position="1">
      <caption>Activate InnoDB</caption>
      <checkbox position="1" id="innodb" is_boolean="yes">
        <caption>Activate InnoDB</caption>
        <default_value>Checked</default_value>
        <description>Enable this option only if you would like to use InnoDB tables.</description>
      </checkbox>
    </group>
    <group position="2">
      <caption>Memory</caption>
      <spinedit position="1" id="innodb_buffer_pool_size">
        <caption>Buffer Pool Size:</caption>
        <default_value>16M</default_value>
        <description>The bigger you set this the less disk I/O is needed to access data in tables. On a dedicated database server you may set this parameter up to 80% of the machine physical memory size. Do not set it too large, though, because competition of the physical memory may cause paging in the operating system.</description>
        <unitcontrolbox type="k;M" />
      </spinedit>
      <spinedit position="2" id="innodb_additional_mem_pool_size">
        <caption>Add. mem Pool Size:</caption>
        <default_value>2M</default_value>
        <description>Size of a memory pool InnoDB uses to store data dictionary information and other internal data structures. A sensible value for this might be 2M, but the more tables you have in your application the more you will need to allocate here. If InnoDB runs out of memory in this pool, it will start to allocate memory from the operating system, and write warning messages to the MySQL error log.</description>
        <unitcontrolbox type="k;M" />
      </spinedit>
      <spinedit position="4" id="innodb_buffer_pool_awe_mem_mb">
        <caption>AWE mem Pool Size:</caption>
